version: "3"
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "O6gGbVBM2t0JaaNG2Ss5n68ZatpH6R3lzAx13DdRuoIsuMn8d0UyecKhOyczLzkW"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  colour-api:
    build: .
    ports:
      - "5200:80"
    environment:
      DBServer: "mssql-server"
